### ISSUE TITLE
Open a surf server

### ISSUE THREAD

**Issue by WillSO93** [redlinecs/RedlineCS#1]
**Is your feature request related to a problem? Please describe.**
yeah i'm banned from nexus and mestro is laggy af.

**Describe the solution you'd like**
a redline surf server.

**Describe alternatives you've considered**
considered moving elsewhere. didn't move.

**Additional context**
me and raq are banned from nexus.

**Comment by b3none** [comment]
Excellent idea, i'll add this to the backlog. Thanks :)

**Comment by b3none** [comment]
Complete! :)
